import { Fragment, useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import TopMenus from '../../components/aikit/TopMenus';
import MainContent from '../../components/aikit/MainContent';
import { SVGICON } from '../../constant/theme';
import { schedulerTable } from '../../constant/alldata';
import PageTitle from '../../layouts/PageTitle';

const numb = [5, 9, 14];

function Scheduled() {
    const [data, setData] = useState(
            document.querySelectorAll("#projects-tbl_wrapper tbody tr")
        );
        const sort = 10;
        const activePag = useRef(0);
        const [test, settest] = useState(0);
        const chageData = (frist, sec) => {
            for (var i = 0; i < data.length; ++i) {
                if (i >= frist && i < sec) {
                    data[i].classList.remove("d-none");
                } else {
                    data[i].classList.add("d-none");
                }
            }
        };
       
       useEffect(() => {
          setData(document.querySelectorAll("#projects-tbl_wrapper tbody tr"));
        }, [test]);
    
       activePag.current === 0 && chageData(0, sort);
       let paggination = Array(Math.ceil(data.length / sort))
          .fill()
          .map((_, i) => i + 1);
        const onClick = (i) => {
            activePag.current = i;
            chageData(activePag.current * sort, (activePag.current + 1) * sort);
            settest(i);
        };
    return (
        <Fragment>
            <PageTitle activeMenu="Scheduled" motherMenu="Home" pageContent={"Scheduled"}/>
            <div className="container">
            <div className="row">
                <div className="col-xl-12">
                    <MainContent detail="This is a demo of AIKit plugin made for you to test the experience of using the plugin. "
                        subtitle="AIKit Scheduled AI Generators allow you to schedule content to be generated by AI. Please review and edit before publishing for best results. This is not a substitute for human editing, but a drafting aid. Happy writing!"
                    />
                    <TopMenus id={2} />
                    <div className="card h-auto">
                        <div className="card-body">
                            <div id="employee-tbl_wrapper" className="table-responsive dataTables_wrapper active-projects style-1">
                                <table id="projects-tbl_wrapper" className="table dataTable dataTables_wrapper no-footer mb-0">
                                    <thead>
                                        <tr>
                                            <th>Description</th>
                                            <th>Keywords</th>
                                            <th>Status</th>
                                            <th>Interval</th>
                                            <th>Last generation</th>
                                            <th>Next generation</th>
                                            <th>Is running</th>
                                            <th>Run count</th>
                                            <th>Max run count</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {schedulerTable.map((item, ind) => (
                                            <tr key={ind}>
                                                <td className="text-black">Write a rat story</td>
                                                <td> {item.keyword} </td>
                                                <td><span className="badge badge-success badge-sm light">Active</span></td>
                                                <td>hourly</td>
                                                <td>4:50 am July 11, 2025</td>
                                                <td>5:50 am July 11, 2025</td>
                                                <td>
                                                    {numb.includes(ind) ?
                                                        <span className="badge badge-success">Yes</span>
                                                        :
                                                        <span className="badge badge-light">No</span>
                                                    }
                                                </td>
                                                <td>1</td>
                                                <td>5</td>
                                                <td className="text-nowrap">
                                                    <Link to={"#"} className="btn btn-primary light btn-sharp"> {SVGICON.blueedit} </Link>{" "}
                                                    <Link to={"#"} className="btn btn-danger light btn-sharp"> {SVGICON.reddelete} </Link>
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                                <div className="d-sm-flex text-center justify-content-between align-items-center">
                            <div className="dataTables_info">
                                Showing {activePag.current * sort + 1} to{" "}
                                {data.length > (activePag.current + 1) * sort
                                    ? (activePag.current + 1) * sort
                                    : data.length}{" "}
                                of {data.length} entries
                            </div>
                            <div
                                className="dataTables_paginate paging_simple_numbers"
                                id="example2_paginate"
                            >
                                <Link
                                    className="paginate_button previous disabled"
                                    to="#"
                                    onClick={() =>
                                    activePag.current > 0 &&
                                    onClick(activePag.current - 1)
                                    }
                                >
                                    <i className="fa-solid fa-angle-left" />
                                </Link>
                                <span>
                                    {paggination.map((number, i) => (
                                    <Link
                                        key={i}
                                        to="#"
                                        className={`paginate_button  ${
                                            activePag.current === i ? "current" : ""
                                        } `}
                                        onClick={() => onClick(i)}
                                    >
                                        {number}
                                    </Link>
                                    ))}
                                </span>
                                <Link
                                    className="paginate_button next"
                                    to="#"
                                    onClick={() =>
                                    activePag.current + 1 < paggination.length &&
                                    onClick(activePag.current + 1)
                                    }
                                >
                                    <i className="fa-solid fa-angle-right" />
                                </Link>
                            </div>
                        </div>
                                {/* <div className="d-sm-flex text-center justify-content-between align-items-center mb-3">
                                    <div className="mb-sm-0 mb-3 dataTables_info pt-0">
                                        <p className="mb-0 text-black">Showing 1 to 9 of 11 entries</p>
                                    </div>
                                    <nav className="dataTables_paginate paging_simple_numbers mb-0">
                                        <ul className="pagination pagination-circle">
                                            <li className="page-item page-indicator"> <Link className="page-link" to={"#"}> <i className="la la-angle-left" /></Link> </li>
                                            <li className="page-item active"><Link className="page-link" to={"#"}>1</Link> </li>
                                            <li className="page-item"><Link className="page-link" to={"#"}>2</Link></li>
                                            <li className="page-item page-indicator"> <Link className="page-link" to={"#"}> <i className="la la-angle-right" /></Link> </li>
                                        </ul>
                                    </nav>
                                </div> */}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </Fragment>
    );
};

export default Scheduled;